# Normalization Evaluator\n\nPart 1: Extraction | Part 2: Rubric | Part 3: Evaluation

In [13]:
!pip install -q pdfplumber google-generativeai pandas
import os
import re
import json
import google.generativeai as genai
import pdfplumber
import pandas as pd
import numpy as np
from IPython.display import display, Markdown

# --- CONFIGURATION ---
# Please set your Gemini API Key here
os.environ["GEMINI_API_KEY"] = "AIzaSyC8Ez9-HJDXr2kaE_nbpVg_IiBK_lhDYZQ" # Placeholder/Example
genai.configure(api_key=os.environ["GEMINI_API_KEY"])
MODEL_NAME = "models/gemini-flash-latest"

In [35]:
import google.generativeai as genai

model = genai.GenerativeModel("models/gemini-flash-latest")
response = model.generate_content("Say OK")
print(response.text)

OK

## Part 1: Extraction Pipeline

In [14]:
def extract_text(input_data):
    """
    input_data: raw text string OR path to PDF/Text file
    """
    text = ""
    if os.path.isfile(str(input_data)):
        if str(input_data).lower().endswith('.pdf'):
            with pdfplumber.open(input_data) as pdf:
                for page in pdf.pages:
                    extracted = page.extract_text()
                    if extracted: text += extracted + "\n"
        else:
            with open(input_data, 'r', encoding='utf-8') as f:
                text = f.read()
    else:
        text = str(input_data)
    return text.strip()

def preprocess(text: str) -> str:
    text = text.lower()
    text = text.replace("→", "->").replace("=>", "->").replace(":", "->")
    text = re.sub(r"\s+", " ", text)
    fillers = ["the table is", "we have", "let us consider", "primary key is", "pk is"]
    for f in fillers:
        text = text.replace(f, "")
    return text.strip()

LLM_PROMPT = """
You are extracting database normalization answers.

STRICT RULES:
- Output ONLY valid JSON
- Do NOT include markdown, comments, or explanations
- Do NOT invent attributes, tables, or dependencies
- If information is missing, use empty lists []
- Attribute names must be lowercase
- Use '->' for functional dependencies
- Follow the JSON format EXACTLY

REQUIRED JSON FORMAT:
{{
  "attribute": [],
  "multivalued": [],
  "compositeattributes": [],
  "fds": [],
  "1nf": [],
  "2nf": [],
  "3nf": [],
  "final_tables": []
}}

Student Answer:
<<<{text}>>>
"""

def extract_json_from_response(text):
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise ValueError(f"No JSON found in response")
    return match.group(0)

def llm_extract_schema(clean_text):
    model = genai.GenerativeModel(MODEL_NAME)
    response = model.generate_content(
        LLM_PROMPT.format(text=clean_text),
        generation_config={"temperature": 0.0, "max_output_tokens": 4096}
    )
    try:
        return json.loads(extract_json_from_response(response.text))
    except Exception as e:
        print(f"Extraction Error: {e}")
        print(f"Raw Output: {response.text}")
        return None

## Part 2 & 3: Rubric Builder and Evaluation Engine

In [15]:
def parse_fds(fd_list):
    parsed = []
    for fd in fd_list:
        if "->" not in fd: continue
        lhs, rhs = fd.split("->")
        parsed.append({
            "lhs": frozenset(a.strip() for a in lhs.split(",")),
            "rhs": frozenset(a.strip() for a in rhs.split(","))
        })
    return parsed

def build_rubric_sheet(ref_schema):
    # Dynamic Scoring based on User Rules
    # FDs: 0.5 per correct FD
    num_fds = len(ref_schema.get('fds', []))
    fd_total = num_fds * 0.5
    
    # Normal Forms (Fixed marks per question as per instructions)
    # 3NF: Transitive(1) + Lossless(2) + Key(1) = 4
    # 1NF: Composite(1) + Multi(1) = 2
    # 2NF: Partial(1) + Lossless(2) + Key(1) = 4
    
    # Final Relations: 0.5 per table
    num_final = len(ref_schema.get('final_tables', []))
    final_total = num_final * 0.5
    
    rubric = {
        "Functional Dependencies": {"max": fd_total, "rule": "0.5 marks per FD"},
        "1NF": {"max": 2.0, "rule": "Composite(1) + Multivalued(1)"},
        "2NF": {"max": 4.0, "rule": "Partial(1) + Lossless(2) + Key(1)"},
        "3NF": {"max": 4.0, "rule": "Transitive(1) + Lossless(2) + Key(1)"},
        "Final Relations": {"max": final_total, "rule": "0.5 marks per Relation"},
        "TOTAL": {"max": fd_total + 2 + 4 + 4 + final_total, "rule": "Sum"}
    }
    
    df = pd.DataFrame.from_dict(rubric, orient='index')
    df.columns = ['Max Marks', 'Scoring Rule']
    return df

In [5]:
class NormalizationEvaluator:
    def __init__(self, ref_schema):
        self.ref = ref_schema
        self.rubric = build_rubric_sheet(ref_schema)
        self.ref_fds_parsed = parse_fds(ref_schema.get('fds', []))
        
    def evaluate(self, student_sub):
        report = []
        total_score = 0
        
        # 1. Functional Dependencies
        stu_fds = parse_fds(student_sub.get('fds', []))
        # Simple match: check if student FD is in ref FD (canonical comparison)
        matched_fds = 0
        missing_fds = []
        for rfd in self.ref_fds_parsed:
            found = False
            for sfd in stu_fds:
                if sfd['lhs'] == rfd['lhs'] and sfd['rhs'] == rfd['rhs']:
                    found = True
                    break
            if found: matched_fds += 1
            else: missing_fds.append(f"{set(rfd['lhs'])}->{set(rfd['rhs'])}")
            
        fd_score = matched_fds * 0.5
        total_score += fd_score
        report.append({
            "Step": "Functional Dependencies", 
            "Score": fd_score, 
            "Max": self.rubric.loc['Functional Dependencies']['Max Marks'],
            "Feedback": f"Matched {matched_fds} FDs. Missing: {missing_fds}" if missing_fds else "All FDs identified."
        })

        # 2. 1NF
        # Attributes check + formatting
        s1nf = student_sub.get('1nf', [])
        score_1nf = 0
        feedback_1nf = []
        # Check if student separated multivalued/composite? 
        # We rely on attribute comparison with Ref 1NF
        ref_1nf_attrs = set(self.ref['1nf'][0]['attributes']) if self.ref['1nf'] else set()
        stu_1nf_attrs = set(s1nf[0]['attributes']) if s1nf else set()
        
        if stu_1nf_attrs == ref_1nf_attrs:
            score_1nf = 2.0 # Full marks
            feedback_1nf.append("Attributes match reference 1NF.")
        else:
            missing = ref_1nf_attrs - stu_1nf_attrs
            extra = stu_1nf_attrs - ref_1nf_attrs
            score_1nf = max(0, 2.0 - (0.5 * len(missing)))
            feedback_1nf.append(f"Attribute mismatch. Missing: {missing}, Extra: {extra}")

        total_score += score_1nf
        report.append({"Step": "1NF", "Score": score_1nf, "Max": 2.0, "Feedback": " ".join(feedback_1nf)})

        # 3. 2NF & 3NF Helper
        def compare_stage(stage_name, max_score):
            ref_tables = self.ref.get(stage_name, [])
            stu_tables = student_sub.get(stage_name, [])
            
            # Canonicalize tables for comparison (sort attributes)
#             ref_str = sorted([str(sorted(t['attributes'])) for t in ref_tables])
#             stu_str = sorted([str(sorted(t['attributes'])) for t in stu_tables])
            
            # Better: Count matches
            matches = 0
            for rt in ref_tables:
                rt_attrs = set(rt['attributes'])
                rt_pk = set(rt.get('pk', []))
                for st in stu_tables:
                    if set(st['attributes']) == rt_attrs:
                        # Check PK
                        if set(st.get('pk', [])) == rt_pk:
                            matches += 1
                        else:
                            matches += 0.5 # Partial credit for attrs match but wrong PK
                        break
            
            # Simple proportional score based on table matches vs expected tables
            # But prompt specifies Breakdown: Partial(1), Lossless(2), Key(1).
            # If all tables match -> Full Marks.
            # If tables mismatch -> Penalize.
            
            if len(ref_tables) == 0: return max_score, "No tables in this stage."
            
            ratio = matches / len(ref_tables)
            stage_score = ratio * max_score
            
            feedback = f"Matched {matches}/{len(ref_tables)} tables correctly."
            return stage_score, feedback

        # 2NF
        s2, f2 = compare_stage('2nf', 4.0)
        total_score += s2
        report.append({"Step": "2NF", "Score": s2, "Max": 4.0, "Feedback": f2})

        # 3NF
        s3, f3 = compare_stage('3nf', 4.0)
        total_score += s3
        report.append({"Step": "3NF", "Score": s3, "Max": 4.0, "Feedback": f3})

        # 4. Final Relations
        ref_final = self.ref.get('final_tables', [])
        stu_final = student_sub.get('final_tables', [])
        
        final_matches = 0
        for rt in ref_final:
            rt_attrs = set(rt['attributes'])
            for st in stu_final:
                if set(st['attributes']) == rt_attrs:
                    final_matches += 1
                    break
                    
        final_score = final_matches * 0.5
        total_score += final_score
        report.append({
            "Step": "Final Relations", 
            "Score": final_score, 
            "Max": self.rubric.loc['Final Relations']['Max Marks'],
            "Feedback": f"Identified {final_matches}/{len(ref_final)} final tables."
        })
        
        return total_score, pd.DataFrame(report)

def evaluate_submission(student_input, reference_schema):
    print("--- 1. Extraction ---")
    raw_text = extract_text(student_input)
    clean_text = dummy_student_text#preprocess(raw_text)
    # Try parsing as JSON first (to support demo/dummy data)
    try:
        student_json = json.loads(clean_text)
    except json.JSONDecodeError:
        # Fallback to LLM extraction
        student_json = llm_extract_schema(clean_text)
    
    if student_json:
        print("Extraction Successful.")
        # print(json.dumps(student_json, indent=2))
        
        print("\n- 2. Rubric Generation ---")
        evaluator = NormalizationEvaluator(reference_schema)
        display(evaluator.rubric)
        
        print("\n- 3. Evaluation Report ---")
        score, report_df = evaluator.evaluate(student_json)
        display(report_df)
        print(f"\nTOTAL SCORE: {score} / {(evaluator.rubric['Max Marks'].sum())/2}")
        
        return score, report_df
    else:
        print("Extraction Failed.")
        return 0, None

## Demo Execution

NameError: name 'report_df' is not defined

In [16]:
# Example Reference Schema (Restaurant)
reference_schema = {
  "attribute": ["order_id", "order_date", "order_time", "total_price", "customer_id", "customer_name", "customer_phone", "customer_address", "restaurant_id", "restaurant_name", "restaurant_location", "restaurant_rating", "item_id", "item_name", "item_category", "item_base_price", "chef_id", "chef_name", "chef_specialty", "quantity", "discount_applied", "item_total"],
  "fds": ["customer_id->customer_name,customer_phone,customer_address", "restaurant_id->restaurant_name,restaurant_location,restaurant_rating", "item_id->item_name,item_category,item_base_price,chef_id", "chef_id->chef_name,chef_specialty", "order_id->order_date,order_time,total_price,customer_id,restaurant_id", "order_id,item_id->quantity,discount_applied,item_total"],
  "1nf": [
    {
      "name": "RESTAURANT_ORDER",
      "attributes": ["order_id", "order_date", "order_time", "total_price", "customer_id", "customer_name", "customer_phone", "customer_address", "restaurant_id", "restaurant_name", "restaurant_location", "restaurant_rating", "item_id", "item_name", "item_category", "item_base_price", "chef_id", "chef_name", "chef_specialty", "quantity", "discount_applied", "item_total"],
      "pk": ["order_id"]
    }
  ],
  "2nf": [
    {"name": "CUSTOMER_INFO", "attributes": ["customer_id", "customer_name", "customer_phone", "customer_address"], "pk": ["customer_id"]},
    {"name": "RESTAURANT_INFO", "attributes": ["restaurant_id", "restaurant_name", "restaurant_location", "restaurant_rating"], "pk": ["restaurant_id"]},
    {"name": "ITEM_INFO", "attributes": ["item_id", "item_name", "item_category", "item_base_price", "chef_id"], "pk": ["item_id"]},
    {"name": "CHEF_INFO", "attributes": ["chef_id", "chef_name", "chef_specialty"], "pk": ["chef_id"]},
    {"name": "ORDER_INFO", "attributes": ["order_id", "order_date", "order_time", "total_price", "customer_id", "restaurant_id"], "pk": ["order_id"]},
    {"name": "ORDER_ITEM", "attributes": ["order_id", "item_id", "quantity", "discount_applied", "item_total"], "pk": ["order_id", "item_id"]}
  ],
  "3nf": [
     {"name": "CUSTOMER_INFO", "attributes": ["customer_id", "customer_name", "customer_phone", "customer_address"], "pk": ["customer_id"]},
    {"name": "RESTAURANT_INFO", "attributes": ["restaurant_id", "restaurant_name", "restaurant_location", "restaurant_rating"], "pk": ["restaurant_id"]},
    {"name": "ITEM_INFO", "attributes": ["item_id", "item_name", "item_category", "item_base_price", "chef_id"], "pk": ["item_id"]},
    {"name": "CHEF_INFO", "attributes": ["chef_id", "chef_name", "chef_specialty"], "pk": ["chef_id"]},
    {"name": "ORDER_INFO", "attributes": ["order_id", "order_date", "order_time", "total_price", "customer_id", "restaurant_id"], "pk": ["order_id"]},
    {"name": "ORDER_ITEM", "attributes": ["order_id", "item_id", "quantity", "discount_applied", "item_total"], "pk": ["order_id", "item_id"]}
  ],
  "final_tables": [
    {"name": "CUSTOMER_INFO", "attributes": ["customer_id", "customer_name", "customer_phone", "customer_address"], "pk": ["customer_id"]},
    {"name": "RESTAURANT_INFO", "attributes": ["restaurant_id", "restaurant_name", "restaurant_location", "restaurant_rating"], "pk": ["restaurant_id"]},
    {"name": "ITEM_INFO", "attributes": ["item_id", "item_name", "item_category", "item_base_price", "chef_id"], "pk": ["item_id"]},
    {"name": "CHEF_INFO", "attributes": ["chef_id", "chef_name", "chef_specialty"], "pk": ["chef_id"]},
    {"name": "ORDER_INFO", "attributes": ["order_id", "order_date", "order_time", "total_price", "customer_id", "restaurant_id"], "pk": ["order_id"]},
    {"name": "ORDER_ITEM", "attributes": ["order_id", "item_id", "quantity", "discount_applied", "item_total"], "pk": ["order_id", "item_id"]}
  ]
}

# Dummy Student Submission (Matches Reference for Demo)
dummy_student_text = """
{
  "attribute": ["order_id", "order_date", "order_time", "total_price", "customer_id", "customer_name", "customer_phone", "customer_address", "restaurant_id", "restaurant_name", "restaurant_location", "restaurant_rating", "item_id", "item_name", "item_category", "item_base_price", "chef_id", "chef_name", "chef_specialty", "quantity", "discount_applied", "item_total"],
  "fds": ["customer_id->customer_name,customer_address", "restaurant_id->restaurant_name,restaurant_location,restaurant_rating", "item_id->item_name,item_category,item_base_price,chef_id", "chef_id->chef_name,chef_specialty", "order_id->order_date,order_time,total_price,customer_id,restaurant_id", "order_id,item_id->quantity,discount_applied,item_total"],
  "1nf": [
    {
      "name": "RESTAURANT_ORDER",
      "attributes": ["order_id", "order_date", "order_time", "total_price", "customer_id", "customer_name", "customer_phone", "customer_address", "restaurant_id", "restaurant_name", "restaurant_location", "restaurant_rating", "item_id", "item_name", "item_category", "item_base_price", "chef_id", "chef_name", "chef_specialty", "quantity", "discount_applied", "item_total"],
      "pk": ["order_id"]
    }
  ],
  "2nf": [
    {"name": "CUSTOMER_INFO", "attributes": ["customer_id", "customer_name", "customer_phone", "customer_address"], "pk": ["customer_id"]},
    {"name": "RESTAURANT_INFO", "attributes": ["restaurant_id", "restaurant_name", "restaurant_location", "restaurant_rating"], "pk": ["restaurant_id"]},
    {"name": "ITEM_INFO", "attributes": ["item_id", "item_name", "item_category", "item_base_price", "chef_id"], "pk": ["item_id"]},
    {"name": "CHEF_INFO", "attributes": ["chef_id", "chef_name", "chef_specialty"], "pk": ["chef_id"]},
    {"name": "ORDER_INFO", "attributes": ["order_id", "order_date", "order_time", "total_price", "customer_id", "restaurant_id"], "pk": ["order_id"]},
    {"name": "ORDER_ITEM", "attributes": ["order_id", "item_id", "quantity", "discount_applied", "item_total"], "pk": ["order_id", "item_id"]}
  ],
  "3nf": [
     {"name": "CUSTOMER_INFO", "attributes": ["customer_id", "customer_name", "customer_phone", "customer_address"], "pk": ["customer_id"]},
    {"name": "RESTAURANT_INFO", "attributes": ["restaurant_id", "restaurant_name", "restaurant_location", "restaurant_rating"], "pk": ["restaurant_id"]},
    {"name": "ITEM_INFO", "attributes": ["item_id", "item_name", "item_category", "item_base_price", "chef_id"], "pk": ["item_id"]},
    {"name": "CHEF_INFO", "attributes": ["chef_id", "chef_name", "chef_specialty"], "pk": ["chef_id"]},
    {"name": "ORDER_INFO", "attributes": ["order_id", "order_date", "order_time", "total_price", "customer_id", "restaurant_id"], "pk": ["order_id"]},
    {"name": "ORDER_ITEM", "attributes": ["order_id", "item_id", "quantity", "discount_applied", "item_total"], "pk": ["order_id", "item_id"]}
  ],
  "final_tables": [
    {"name": "CUSTOMER_INFO", "attributes": ["customer_id", "customer_name", "customer_phone", "customer_address"], "pk": ["customer_id"]},
    {"name": "RESTAURANT_INFO", "attributes": ["restaurant_id", "restaurant_name", "restaurant_location", "restaurant_rating"], "pk": ["restaurant_id"]},
    {"name": "ITEM_INFO", "attributes": ["item_id", "item_name", "item_category", "item_base_price", "chef_id"], "pk": ["item_id"]},
    {"name": "CHEF_INFO", "attributes": ["chef_id", "chef_name", "chef_specialty"], "pk": ["chef_id"]},
    {"name": "ORDER_INFO", "attributes": ["order_id", "order_date", "order_time", "total_price", "customer_id", "restaurant_id"], "pk": ["order_id"]},
    {"name": "ORDER_ITEM", "attributes": ["order_id", "item_id", "quantity", "discount_applied", "item_total"], "pk": ["order_id", "item_id"]}
  ]
}
"""

In [23]:

a,b=evaluate_submission(dummy_student_text, reference_schema)

--- 1. Extraction ---
Extraction Successful.

- 2. Rubric Generation ---

                         Max Marks                          Scoring Rule
Functional Dependencies        3.0                      0.5 marks per FD
1NF                            2.0         Composite(1) + Multivalued(1)
2NF                            4.0     Partial(1) + Lossless(2) + Key(1)
3NF                            4.0  Transitive(1) + Lossless(2) + Key(1)
Final Relations                3.0                0.5 marks per Relation
TOTAL                         16.0                                   Sum

- 3. Evaluation Report ---

,Step,Score,Max,Feedback
0,Functional Dependencies,2.5,3.0,"Matched 5 FDs. Missing: [""{'customer_id'}->{'c..."
1,1NF,2.0,2.0,Attributes match reference 1NF.
2,2NF,4.0,4.0,Matched 6/6 tables correctly.
3,3NF,4.0,4.0,Matched 6/6 tables correctly.
4,Final Relations,3.0,3.0,Identified 6/6 final tables.

TOTAL SCORE: 15.5 / 16.0

In [24]:
a

15.5

In [27]:
b

,Step,Score,Max,Feedback
0,Functional Dependencies,2.5,3.0,"Matched 5 FDs. Missing: [""{'customer_id'}->{'c..."
1,1NF,2.0,2.0,Attributes match reference 1NF.
2,2NF,4.0,4.0,Matched 6/6 tables correctly.
3,3NF,4.0,4.0,Matched 6/6 tables correctly.
4,Final Relations,3.0,3.0,Identified 6/6 final tables.

In [29]:
for i in b["Feedback"]:
    print(i)

Matched 5 FDs. Missing: ["{'customer_id'}->{'customer_address', 'customer_phone', 'customer_name'}"]
Attributes match reference 1NF.
Matched 6/6 tables correctly.
Matched 6/6 tables correctly.
Identified 6/6 final tables.

In [19]:
# Run the evaluator
evaluate_submission(dummy_student_text, reference_schema)

--- 1. Extraction ---
Extraction Successful.

- 2. Rubric Generation ---

                         Max Marks                          Scoring Rule
Functional Dependencies        3.0                      0.5 marks per FD
1NF                            2.0         Composite(1) + Multivalued(1)
2NF                            4.0     Partial(1) + Lossless(2) + Key(1)
3NF                            4.0  Transitive(1) + Lossless(2) + Key(1)
Final Relations                3.0                0.5 marks per Relation
TOTAL                         16.0                                   Sum

- 3. Evaluation Report ---

,Step,Score,Max,Feedback
0,Functional Dependencies,2.5,3.0,"Matched 5 FDs. Missing: [""{'customer_id'}->{'c..."
1,1NF,2.0,2.0,Attributes match reference 1NF.
2,2NF,4.0,4.0,Matched 6/6 tables correctly.
3,3NF,4.0,4.0,Matched 6/6 tables correctly.
4,Final Relations,3.0,3.0,Identified 6/6 final tables.

TOTAL SCORE: 15.5 / 16.0

(15.5,
                       Step  Score  Max  \
 0  Functional Dependencies    2.5  3.0
 1                      1NF    2.0  2.0
 2                      2NF    4.0  4.0
 3                      3NF    4.0  4.0
 4          Final Relations    3.0  3.0

                                             Feedback
 0  Matched 5 FDs. Missing: ["{'customer_id'}->{'c...
 1                    Attributes match reference 1NF.
 2                      Matched 6/6 tables correctly.
 3                      Matched 6/6 tables correctly.
 4                       Identified 6/6 final tables.  )

In [18]:
gold_schema2={
  "attribute": ["person_id", "name", "phone_no", "department", "approval_required", "request_id", "request_date", "status", "description", "service_type_id", "service_type_name", "service_category", "staff_id", "staff_name", "staff_phone", "staff_specialization", "hod_id", "hod_name", "approval_status"],
  "fds": ["person_id->name,phone_no,department,approval_required", "request_id->request_date,status,description", "service_type_id->service_type_name,service_category", "staff_id->staff_name,staff_phone,staff_specialization", "hod_id->hod_name", "request_id->staff_id,hod_id,approval_status"],
  "1nf": [
    {
      "name": "icts",
      "attributes": ["person_id", "name", "phone_no", "department", "approval_required", "request_id", "request_date", "status", "description", "service_type_id", "service_type_name", "service_category", "staff_id", "staff_name", "staff_phone", "staff_specialization", "hod_id", "hod_name", "approval_status"],
      "pk": ["person_id"]
    }
  ],
  "2nf": [
    {
      "name": "Person",
      "attributes": ["person_id", "name", "phone_no", "department", "approval_required"],
      "pk": ["person_id"]
    },
    {
      "name": "Request",
      "attributes": ["request_id", "request_date", "status", "description"],
      "pk": ["request_id"]
    },
    {
      "name": "ServiceType",
      "attributes": ["service_type_id", "service_type_name", "service_category"],
      "pk": ["service_type_id"]
    },
    {
      "name": "Staff",
      "attributes": ["staff_id", "staff_name", "staff_phone", "staff_specialization"],
      "pk": ["staff_id"]
    },
    {
      "name": "HOD",
      "attributes": ["hod_id", "hod_name"],
      "pk": ["hod_id"]
    },
    {
      "name": "Approval",
      "attributes": ["request_id", "staff_id", "hod_id", "approval_status"],
      "pk": ["request_id"]
    }
  ],
  "3nf": [
    {
      "name": "Person",
      "attributes": ["person_id", "name", "phone_no", "department", "approval_required"],
      "pk": ["person_id"]
    },
    {
      "name": "Request",
      "attributes": ["request_id", "request_date", "status", "description"],
      "pk": ["request_id"]
    },
    {
      "name": "ServiceType",
      "attributes": ["service_type_id", "service_type_name", "service_category"],
      "pk": ["service_type_id"]
    },
    {
      "name": "Staff",
      "attributes": ["staff_id", "staff_name", "staff_phone", "staff_specialization"],
      "pk": ["staff_id"]
    },
    {
      "name": "HOD",
      "attributes": ["hod_id", "hod_name"],
      "pk": ["hod_id"]
    },
    {
      "name": "Approval",
      "attributes": ["request_id", "staff_id", "hod_id", "approval_status"],
      "pk": ["request_id"]
    }
  ],
  "final_tables": [
    {
      "name": "Person",
      "attributes": ["person_id", "name", "phone_no", "department", "approval_required"],
      "pk": ["person_id"]
    },
    {
      "name": "Request",
      "attributes": ["request_id", "request_date", "status", "description"],
      "pk": ["request_id"]
    },
    {
      "name": "ServiceType",
      "attributes": ["service_type_id", "service_type_name", "service_category"],
      "pk": ["service_type_id"]
    },
    {
      "name": "Staff",
      "attributes": ["staff_id", "staff_name", "staff_phone", "staff_specialization"],
      "pk": ["staff_id"]
    },
    {
      "name": "HOD",
      "attributes": ["hod_id", "hod_name"],
      "pk": ["hod_id"]
    },
    {
      "name": "Approval",
      "attributes": ["request_id", "staff_id", "hod_id", "approval_status"],
      "pk": ["request_id"]
    }
  ]
}
 
     
student_sub={
  "attribute": [
    "person_id",
    "name",
    "phone_no",
    "department",
    "approval_required",
    "request_id",
    "request_date",
    "status",
    "description",
    "service_type_id",
    "service_type_name",
    "service_category",
    "staff_id",
    "staff_name",
    "staff_phone",
    "staff_specialization",
    "hod_id",
    "hod_name",
    "approval_status"
  ],
  "multivalued": [
    "phone_no",
    "staff_phone"
  ],
  "compositeattributes": [],
  "fds": [
    "person_id->name,phone_no,department,approval_required",
    "request_id->request_date,status,description",
    "service_type_id->service_type_name,service_category",
    "staff_id->staff_name,staff_phone,staff_specialization",
    "hod_id->hod_name",
    "request_id->staff_id,hod_id,approval_status"
  ],
  "1nf": [
    {"name": "Person", "attributes": ["person_id", "name", "phone_no", "department", "approval_required"], "pk": ["person_id"]},
    {"name": "Person_Contact", "attributes": ["person_id", "contact_number"], "pk": ["person_id", "contact_number"]},
    {"name": "Service_Request", "attributes": ["request_id", "person_id", "service_type_id", "request_date", "status", "description"], "pk": ["request_id"]},
    {"name": "Service_Type", "attributes": ["service_type_id", "service_type_name", "service_category"], "pk": ["service_type_id"]},
    {"name": "Staff", "attributes": ["staff_id", "staff_name", "staff_phone", "staff_specialization"], "pk": ["staff_id"]},
    {"name": "Staff_Contact", "attributes": ["staff_id", "contact_number"], "pk": ["staff_id", "contact_number"]},
    {"name": "HOD", "attributes": ["hod_id", "hod_name", "department_id"], "pk": ["hod_id"]},
    {"name": "Request_Handling", "attributes": ["request_id", "staff_id", "hod_id", "approval_status"], "pk": ["request_id"]}
  ],
  "2nf": [
    {"name": "Person", "attributes": ["person_id", "name", "phone_no", "department", "approval_required"], "pk": ["person_id"]},
    {"name": "Person_Contact", "attributes": ["person_id", "contact_number"], "pk": ["person_id", "contact_number"]},
    {"name": "Service_Request", "attributes": ["request_id", "person_id", "service_type_id", "request_date", "status", "description"], "pk": ["request_id"]},
    {"name": "Service_Type", "attributes": ["service_type_id", "service_type_name", "service_category"], "pk": ["service_type_id"]},
    {"name": "Staff", "attributes": ["staff_id", "staff_name", "staff_phone", "staff_specialization"], "pk": ["staff_id"]},
    {"name": "Staff_Contact", "attributes": ["staff_id", "contact_number"], "pk": ["staff_id", "contact_number"]},
    {"name": "HOD", "attributes": ["hod_id", "hod_name", "department_id"], "pk": ["hod_id"]},
    {"name": "Request_Handling", "attributes": ["request_id", "staff_id", "hod_id", "approval_status"], "pk": ["request_id"]}
  ],
  "3nf": [
    {"name": "Person", "attributes": ["person_id", "name", "department_id", "approval_required"], "pk": ["person_id"]},
    {"name": "Person_Contact", "attributes": ["person_id", "contact_number"], "pk": ["person_id", "contact_number"]},
    {"name": "Department", "attributes": ["department_id", "department_name"], "pk": ["department_id"]},
    {"name": "Service_Request", "attributes": ["request_id", "person_id", "service_type_id", "request_date", "status", "description"], "pk": ["request_id"]},
    {"name": "Service_Type", "attributes": ["service_type_id", "service_type_name", "service_category"], "pk": ["service_type_id"]},
    {"name": "Staff", "attributes": ["staff_id", "staff_name", "staff_department_id", "staff_specialization"], "pk": ["staff_id"]},
    {"name": "Staff_Contact", "attributes": ["staff_id", "contact_number"], "pk": ["staff_id", "contact_number"]},
    {"name": "HOD", "attributes": ["hod_id", "hod_name", "department_id"], "pk": ["hod_id"]},
    {"name": "Request_Handling", "attributes": ["request_id", "staff_id", "hod_id", "approval_status"], "pk": ["request_id"]}
  ],
  "final_tables": [
    {"name": "Person", "attributes": ["person_id", "name", "department_id", "approval_required"], "pk": ["person_id"]},
    {"name": "Person_Contact", "attributes": ["person_id", "contact_number"], "pk": ["person_id", "contact_number"]},
    {"name": "Department", "attributes": ["department_id", "department_name"], "pk": ["department_id"]},
    {"name": "Service_Request", "attributes": ["request_id", "person_id", "service_type_id", "request_date", "status", "description"], "pk": ["request_id"]},
    {"name": "Service_Type", "attributes": ["service_type_id", "service_type_name", "service_category"], "pk": ["service_type_id"]},
    {"name": "Staff", "attributes": ["staff_id", "staff_name", "staff_department_id", "staff_specialization"], "pk": ["staff_id"]},
    {"name": "Staff_Contact", "attributes": ["staff_id", "contact_number"], "pk": ["staff_id", "contact_number"]},
    {"name": "HOD", "attributes": ["hod_id", "hod_name", "department_id"], "pk": ["hod_id"]},
    {"name": "Request_Handling", "attributes": ["request_id", "staff_id", "hod_id", "approval_status"], "pk": ["request_id"]}
  ]
}
student_sub2={
  "attribute": [
    "person_id",
    "name",
    "phone_no",
    "department",
    "approval_required",
    "request_id",
    "request_date",
    "status",
    "description",
    "service_type_id",
    "service_type_name",
    "service_category",
    "staff_id",
    "staff_name",
    "staff_phone",
    "staff_specialization",
    "hod_id",
    "hod_name",
    "approval_status"
  ],
  "multivalued": [
    "phone_no",
    "staff_phone"
  ],
  "compositeattributes": [],
  "fds": [
    "person_id->name,phone_no,department,approval_required",
    "request_id->request_date,status,description",
    "service_type_id->service_type_name,service_category",
    "staff_id->staff_name,staff_phone,staff_specialization",
    "hod_id->hod_name",
    "request_id->staff_id,hod_id,approval_status"
  ],
  "1nf": [
    {"name": "Person", "attributes": ["person_id", "name", "phone_no", "department", "approval_required"], "pk": ["person_id"]},
    {"name": "Person_Contact", "attributes": ["person_id", "contact_number"], "pk": ["person_id", "contact_number"]},
    {"name": "Service_Request", "attributes": ["request_id", "person_id", "service_type_id", "request_date", "status", "description"], "pk": ["request_id"]},
    {"name": "Service_Type", "attributes": ["service_type_id", "service_type_name", "service_category"], "pk": ["service_type_id"]},
    {"name": "Staff", "attributes": ["staff_id", "staff_name", "staff_phone", "staff_specialization"], "pk": ["staff_id"]},
    {"name": "Staff_Contact", "attributes": ["staff_id", "contact_number"], "pk": ["staff_id", "contact_number"]},
    {"name": "HOD", "attributes": ["hod_id", "hod_name", "department_id"], "pk": ["hod_id"]},
    {"name": "Request_Handling", "attributes": ["request_id", "staff_id", "hod_id", "approval_status"], "pk": ["request_id"]}
  ],
  "2nf": [
    {"name": "Person", "attributes": ["person_id", "name", "phone_no", "department", "approval_required"], "pk": ["person_id"]},
    {"name": "Person_Contact", "attributes": ["person_id", "contact_number"], "pk": ["person_id", "contact_number"]},
    {"name": "Service_Request", "attributes": ["request_id", "person_id", "service_type_id", "request_date", "status", "description"], "pk": ["request_id"]},
    {"name": "Service_Type", "attributes": ["service_type_id", "service_type_name", "service_category"], "pk": ["service_type_id"]},
    {"name": "Staff", "attributes": ["staff_id", "staff_name", "staff_phone", "staff_specialization"], "pk": ["staff_id"]},
    {"name": "Staff_Contact", "attributes": ["staff_id", "contact_number"], "pk": ["staff_id", "contact_number"]},
    {"name": "HOD", "attributes": ["hod_id", "hod_name", "department_id"], "pk": ["hod_id"]},
    {"name": "Request_Handling", "attributes": ["request_id", "staff_id", "hod_id", "approval_status"], "pk": ["request_id"]}
  ],
  "3nf": [
    {"name": "Person", "attributes": ["person_id", "name", "department_id", "approval_required"], "pk": ["person_id"]},
    {"name": "Person_Contact", "attributes": ["person_id", "contact_number"], "pk": ["person_id", "contact_number"]},
    {"name": "Department", "attributes": ["department_id", "department_name"], "pk": ["department_id"]},
    {"name": "Service_Request", "attributes": ["request_id", "person_id", "service_type_id", "request_date", "status", "description"], "pk": ["request_id"]},
    {"name": "Service_Type", "attributes": ["service_type_id", "service_type_name", "service_category"], "pk": ["service_type_id"]},
    {"name": "Staff", "attributes": ["staff_id", "staff_name", "staff_department_id", "staff_specialization"], "pk": ["staff_id"]},
    {"name": "Staff_Contact", "attributes": ["staff_id", "contact_number"], "pk": ["staff_id", "contact_number"]},
    {"name": "HOD", "attributes": ["hod_id", "hod_name", "department_id"], "pk": ["hod_id"]},
    {"name": "Request_Handling", "attributes": ["request_id", "staff_id", "hod_id", "approval_status"], "pk": ["request_id"]}
  ],
  "final_tables": [
    {"name": "Person", "attributes": ["person_id", "name", "department_id", "approval_required"], "pk": ["person_id"]},
    {"name": "Person_Contact", "attributes": ["person_id", "contact_number"], "pk": ["person_id", "contact_number"]},
    {"name": "Department", "attributes": ["department_id", "department_name"], "pk": ["department_id"]},
    {"name": "Service_Request", "attributes": ["request_id", "person_id", "service_type_id", "request_date", "status", "description"], "pk": ["request_id"]},
    {"name": "Service_Type", "attributes": ["service_type_id", "service_type_name", "service_category"], "pk": ["service_type_id"]},
    {"name": "Staff", "attributes": ["staff_id", "staff_name", "staff_department_id", "staff_specialization"], "pk": ["staff_id"]},
    {"name": "Staff_Contact", "attributes": ["staff_id", "contact_number"], "pk": ["staff_id", "contact_number"]},
    {"name": "HOD", "attributes": ["hod_id", "hod_name"], "pk": ["hod_id"]},
    {"name": "Request_Handling", "attributes": ["request_id", "staff_id", "hod_id", "approval_status"], "pk": ["request_id"]}
  ]
}

In [102]:
gold_schema2ans="""{
  "attribute": ["person_id", "name", "phone_no", "department", "approval_required", "request_id", "request_date", "status", "description", "service_type_id", "service_type_name", "service_category", "staff_id", "staff_name", "staff_phone", "staff_specialization", "hod_id", "hod_name", "approval_status"],
  "fds": ["person_id->name,phone_no,department,approval_required", "request_id->request_date,status,description", "service_type_id->service_type_name,service_category", "staff_id->staff_name,staff_phone,staff_specialization", "hod_id->hod_name", "request_id->staff_id,hod_id,approval_status"],
  "1nf": [
    {
      "name": "icts",
      "attributes": ["person_id", "name", "phone_no", "department", "approval_required", "request_id", "request_date", "status", "description", "service_type_id", "service_type_name", "service_category", "staff_id", "staff_name", "staff_phone", "staff_specialization", "hod_id", "hod_name", "approval_status"],
      "pk": ["person_id"]
    }
  ],
  "2nf": [
    {
      "name": "Person",
      "attributes": ["person_id", "name", "phone_no", "department", "approval_required"],
      "pk": ["person_id"]
    },
    {
      "name": "Request",
      "attributes": ["request_id", "request_date", "status", "description"],
      "pk": ["request_id"]
    },
    {
      "name": "ServiceType",
      "attributes": ["service_type_id", "service_type_name", "service_category"],
      "pk": ["service_type_id"]
    },
    {
      "name": "Staff",
      "attributes": ["staff_id", "staff_name", "staff_phone", "staff_specialization"],
      "pk": ["staff_id"]
    },
    {
      "name": "HOD",
      "attributes": ["hod_id", "hod_name"],
      "pk": ["hod_id"]
    },
    {
      "name": "Approval",
      "attributes": ["request_id", "staff_id", "hod_id", "approval_status"],
      "pk": ["request_id"]
    }
  ],
  "3nf": [
    {
      "name": "Person",
      "attributes": ["person_id", "name", "phone_no", "department", "approval_required"],
      "pk": ["person_id"]
    },
    {
      "name": "Request",
      "attributes": ["request_id", "request_date", "status", "description"],
      "pk": ["request_id"]
    },
    {
      "name": "ServiceType",
      "attributes": ["service_type_id", "service_type_name", "service_category"],
      "pk": ["service_type_id"]
    },
    {
      "name": "Staff",
      "attributes": ["staff_id", "staff_name", "staff_phone", "staff_specialization"],
      "pk": ["staff_id"]
    },
    {
      "name": "HOD",
      "attributes": ["hod_id", "hod_name"],
      "pk": ["hod_id"]
    },
    {
      "name": "Approval",
      "attributes": ["request_id", "staff_id", "hod_id", "approval_status"],
      "pk": ["request_id"]
    }
  ],
  "final_tables": [
    {
      "name": "Person",
      "attributes": ["person_id", "name", "phone_no", "department", "approval_required"],
      "pk": ["person_id"]
    },
    {
      "name": "Request",
      "attributes": ["request_id", "request_date", "status", "description"],
      "pk": ["request_id"]
    },
    {
      "name": "ServiceType",
      "attributes": ["service_type_id", "service_type_name", "service_category"],
      "pk": ["service_type_id"]
    },
    {
      "name": "Staff",
      "attributes": ["staff_id", "staff_name", "staff_phone", "staff_specialization"],
      "pk": ["staff_id"]
    },
    {
      "name": "HOD",
      "attributes": ["hod_id", "hod_name"],
      "pk": ["hod_id"]
    },
    {
      "name": "Approval",
      "attributes": ["request_id", "staff_id", "hod_id", "approval_status"],
      "pk": ["request_id"]
    }
  ]
}"""

In [103]:
evaluate_submission(gold_schema2ans, gold_schema2)

--- 1. Extraction ---
Extraction Successful.

- 2. Rubric Generation ---

                         Max Marks                          Scoring Rule
Functional Dependencies        3.0                      0.5 marks per FD
1NF                            2.0         Composite(1) + Multivalued(1)
2NF                            4.0     Partial(1) + Lossless(2) + Key(1)
3NF                            4.0  Transitive(1) + Lossless(2) + Key(1)
Final Relations                3.0                0.5 marks per Relation
TOTAL                         16.0                                   Sum

- 3. Evaluation Report ---

,Step,Score,Max,Feedback
0,Functional Dependencies,0.0,3.0,"Matched 0 FDs. Missing: [""{'person_id'}->{'app..."
1,1NF,0.0,2.0,Attribute mismatch. Missing: {'staff_specializ...
2,2NF,0.0,4.0,Matched 0/6 tables correctly.
3,3NF,0.0,4.0,Matched 0/6 tables correctly.
4,Final Relations,0.0,3.0,Identified 0/6 final tables.

TOTAL SCORE: 0.0 / 16.0

(0.0,
                       Step  Score  Max  \
 0  Functional Dependencies    0.0  3.0
 1                      1NF    0.0  2.0
 2                      2NF    0.0  4.0
 3                      3NF    0.0  4.0
 4          Final Relations    0.0  3.0

                                             Feedback
 0  Matched 0 FDs. Missing: ["{'person_id'}->{'app...
 1  Attribute mismatch. Missing: {'staff_specializ...
 2                      Matched 0/6 tables correctly.
 3                      Matched 0/6 tables correctly.
 4                       Identified 0/6 final tables.  )

NameError: name 'report' is not defined